swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /v1/devices/octo/report:
    post:
      operationId: Report.Process
      tags:
        - Report
      summary: Processes an Octo sensor report.
      description: Processes an Octo sensor report.
      parameters:
        - name: report
          in: body
          description: Report to process.
          required: True
          schema:
            type: object
            properties:
              payload_raw:
                type: string
                description: Raw sensor payload.
              hardware_serial:
                type: string
                description: Device ID (DevEUI).
              metadata:
                type: object
                description: Message metadata.
                properties:
                  time:
                    type: string
                    description: Time at which the message was received.
      responses:
        201:
          description: Successfully processed the sensor report.


